import type { Salon } from "./types";

/** Pre-verified Unsplash URLs only */
const IMG = {
  salon: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&h=450&q=80",
  hair: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=800&h=450&q=80",
  grooming: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&h=450&q=80",
  beauty: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&h=450&q=80",
  spa: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&h=450&q=80",
  bridal: "https://images.unsplash.com/photo-1596704017235-d974d69c0b59?auto=format&fit=crop&w=800&h=450&q=80",
  nails: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&h=450&q=80",
  premium: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=800&h=450&q=80",
  barbershop: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&h=450&q=80",
  luxury: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&h=450&q=80",
  makeup: "https://images.unsplash.com/photo-1484291470158-b8f8d608850d?auto=format&fit=crop&w=800&h=450&q=80",
};

const GALLERY_SALON = "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=400&h=300&q=80";
const GALLERY_SPA = "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=400&h=300&q=80";
const GALLERY_MAKEUP = "https://images.unsplash.com/photo-1484291470158-b8f8d608850d?auto=format&fit=crop&w=400&h=300&q=80";

export const SALONS: Salon[] = [
  // ── Bandra ──────────────────────────────────────────────────────────────
  {
    id: "glam-studio-bandra",
    name: "Glam Studio Bandra",
    area: "Bandra West",
    address: "42 Hill Road, Near Bandra Station West, Mumbai 400050",
    lat: 19.0596, lng: 72.8295,
    phone: "+919876543210",
    whatsapp: "919876543210",
    email: "hello@glamstudiobandra.in",
    website: "https://glamstudiobandra.in",
    rating: 4.8, reviewCount: 312,
    priceLevel: 3,
    image: IMG.luxury,
    gallery: [IMG.salon, IMG.hair, IMG.makeup],
    tags: ["Luxury", "Hair", "Bridal", "Keratin", "Blowout"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: false,
    amenities: ["AC", "WiFi", "Bridal Suite", "Parking", "Coffee Bar"],
    description: "Mumbai's premier luxury salon destination. Known for celebrity clientele and flawless bridal transformations.",
    established: 2015,
    specialization: "Celebrity Hair Styling & Bridal Makeup",
    services: [
      { id: "gs1", name: "Signature Haircut & Blowout", durationMin: 60, price: 1500, category: "hair" },
      { id: "gs2", name: "Keratin & Smoothing Treatment", durationMin: 180, price: 5500, category: "hair" },
      { id: "gs3", name: "Bridal Makeup (HD)", durationMin: 120, price: 8500, category: "bridal" },
      { id: "gs4", name: "Bridal Makeup Trial", durationMin: 90, price: 3500, category: "bridal" },
      { id: "gs5", name: "Balayage Highlights", durationMin: 180, price: 7000, category: "hair" },
    ],
  },
  {
    id: "sutra-bandra",
    name: "Sutra Hair Studio",
    area: "Bandra West",
    address: "18 Linking Road, Near Cafe Coffee Day, Bandra West, Mumbai 400050",
    lat: 19.0553, lng: 72.8312,
    phone: "+919876543211",
    whatsapp: "919876543211",
    rating: 4.7, reviewCount: 228,
    priceLevel: 2,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.salon, IMG.beauty],
    tags: ["Hair Experts", "Color Specialists", "Balayage", "Affordable"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["AC", "Sanitized Tools", "Steam"],
    description: "Bandra's favourite neighborhood hair studio. Expert colorists and stylists who understand Mumbai's unique hair needs.",
    established: 2018,
    specialization: "Hair Coloring & Precision Cuts",
    services: [
      { id: "ss1", name: "Unisex Haircut", durationMin: 45, price: 600, category: "hair" },
      { id: "ss2", name: "Full Hair Color", durationMin: 90, price: 2500, category: "hair" },
      { id: "ss3", name: "Balayage Art", durationMin: 150, price: 4500, category: "hair" },
      { id: "ss4", name: "Deep Conditioning Treatment", durationMin: 45, price: 800, category: "hair" },
      { id: "ss5", name: "Hair Spa Combo", durationMin: 75, price: 1200, category: "hair" },
    ],
  },
  {
    id: "rose-glow-bandra",
    name: "Rose Glow Beauty Lounge",
    area: "Bandra West",
    address: "Ground Floor, Bandra Plaza, Waterfield Road, Mumbai 400050",
    lat: 19.0580, lng: 72.8280,
    phone: "+919876543212",
    rating: 4.6, reviewCount: 175,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.salon, IMG.grooming],
    tags: ["Skin Care", "Facials", "Makeup", "Waxing"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["AC", "Organic Products", "Signature Facials"],
    description: "Your complete beauty destination. Specializing in glowing skin treatments and effortless everyday glam.",
    established: 2019,
    specialization: "Glow Facials & Skin Analysis",
    services: [
      { id: "rg1", name: "Signature Glow Facial", durationMin: 60, price: 1200, category: "skin" },
      { id: "rg2", name: "Gold Facial", durationMin: 75, price: 2500, category: "skin" },
      { id: "rg3", name: "Party Makeup", durationMin: 60, price: 2000, category: "makeup" },
      { id: "rg4", name: "Threading & Waxing Combo", durationMin: 30, price: 400, category: "skin" },
      { id: "rg5", name: "Anti-Aging Facial", durationMin: 90, price: 3000, category: "skin" },
    ],
  },
  {
    id: "brow-bar-bandra",
    name: "Brow Bar by Ria",
    area: "Bandra West",
    address: "Pali Naka, Bandra West, Mumbai 400050",
    lat: 19.0540, lng: 72.8330,
    phone: "+919876543213",
    rating: 4.5, reviewCount: 98,
    priceLevel: 1,
    image: IMG.nails,
    gallery: [IMG.nails, IMG.beauty],
    tags: ["Brows", "Lashes", "Nails", "Quick"],
    openHours: "11:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Walk-in OK", "Lash Extensions", "Brow Lamination"],
    description: "Dedicated brow and lash artistry studio. Perfect arches, stunning lashes — the details that make all the difference.",
    established: 2021,
    specialization: "Brow Design & Lash Extensions",
    services: [
      { id: "bb1", name: "Brow Shaping & Tint", durationMin: 30, price: 500, category: "grooming" },
      { id: "bb2", name: "Brow Lamination", durationMin: 45, price: 1200, category: "grooming" },
      { id: "bb3", name: "Classic Lash Extensions", durationMin: 90, price: 2500, category: "grooming" },
      { id: "bb4", name: "Gel Manicure", durationMin: 45, price: 700, category: "nails" },
      { id: "bb5", name: "Lip Tint", durationMin: 20, price: 400, category: "makeup" },
    ],
  },

  // ── Juhu ──────────────────────────────────────────────────────────────────
  {
    id: "bridal-bliss-juhu",
    name: "Bridal Bliss Juhu",
    area: "Juhu",
    address: "14 Juhu Tara Road, Near Juhu Beach, Mumbai 400049",
    lat: 19.1075, lng: 72.8263,
    phone: "+919811223344",
    whatsapp: "919811223344",
    email: "bridal@blissjuhu.com",
    website: "https://bridalblissjuhu.com",
    rating: 4.9, reviewCount: 428,
    priceLevel: 3,
    image: IMG.bridal,
    gallery: [IMG.bridal, IMG.makeup, IMG.hair, IMG.salon],
    beforeAfter: [
      { before: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=300&h=400&q=80", after: "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=300&h=400&q=80", caption: "Wedding Reception Look — Priya S." },
      { before: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=300&h=400&q=80", after: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=300&h=400&q=80", caption: "Engagement Glam — Ananya K." },
    ],
    tags: ["Bridal", "Mehendi", "Wedding", "HD Makeup", "Celebrity"],
    openHours: "9:00 AM – 7:00 PM",
    homeService: true,
    amenities: ["Bridal Suite", "HD Cameras", "Home Visits", "Air-Conditioned Van"],
    description: "Mumbai's #1 bridal destination. Featured in Brides Today magazine. Trusted by 500+ brides for their D-day transformations.",
    established: 2012,
    specialization: "Bridal & Event Makeup",
    services: [
      { id: "bb1", name: "Bridal Makeup (Premium)", durationMin: 180, price: 15000, category: "bridal" },
      { id: "bb2", name: "Engagement Look", durationMin: 90, price: 6000, category: "bridal" },
      { id: "bb3", name: "Mehendi Ceremony Glam", durationMin: 60, price: 4000, category: "bridal" },
      { id: "bb4", name: "Haldi Cleanup", durationMin: 45, price: 2500, category: "skin" },
      { id: "bb5", name: "Reception Touch-up Service", durationMin: 30, price: 2000, category: "bridal" },
      { id: "bb6", name: "Full Body Pre-Bridal Package", durationMin: 300, price: 25000, category: "bridal" },
    ],
  },
  {
    id: "serene-spa-juhu",
    name: "Serene Spa & Wellness",
    area: "Juhu",
    address: "Opp. Juhu Beach, 1st Floor, Juhu Scheme, Mumbai 400049",
    lat: 19.1050, lng: 72.8240,
    phone: "+919811223345",
    rating: 4.7, reviewCount: 203,
    priceLevel: 2,
    image: IMG.spa,
    gallery: [IMG.spa, IMG.salon],
    tags: ["Spa", "Massage", "Ayurvedic", "Relaxation"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: true,
    amenities: ["Steam Room", "Couple Suites", "Ayurvedic Treatments", "Reflexology"],
    description: "Escape the chaos of Mumbai at our award-winning spa. From traditional Ayurvedic rituals to modern wellness therapies.",
    established: 2016,
    specialization: "Wellness & Stress Relief",
    services: [
      { id: "ss1", name: "Swedish Massage 60min", durationMin: 60, price: 1800, category: "spa" },
      { id: "ss2", name: "Deep Tissue Therapy", durationMin: 90, price: 2500, category: "spa" },
      { id: "ss3", name: "Aromatherapy Journey", durationMin: 120, price: 3500, category: "spa" },
      { id: "ss4", name: "Couple's Retreat", durationMin: 120, price: 5500, category: "spa" },
      { id: "ss5", name: "Foot Reflexology", durationMin: 45, price: 1000, category: "spa" },
    ],
  },
  {
    id: "style-lounge-juhu",
    name: "Style Lounge Juhu",
    area: "Juhu",
    address: "7th Road, Juhu, Mumbai 400049",
    lat: 19.1090, lng: 72.8280,
    phone: "+919811223346",
    rating: 4.4, reviewCount: 134,
    priceLevel: 1,
    image: IMG.salon,
    gallery: [IMG.salon, IMG.hair],
    tags: ["Hair", "Affordable", "Family", "Quick Cuts"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Kids Corner", "AC", "Quick Service"],
    description: "Juhu's trusted neighborhood salon for the whole family. Quick, quality cuts at prices that won't break the bank.",
    established: 2020,
    specialization: "Family Hair Care",
    services: [
      { id: "sl1", name: "Women's Haircut", durationMin: 45, price: 450, category: "hair" },
      { id: "sl2", name: "Men's Haircut", durationMin: 30, price: 300, category: "grooming" },
      { id: "sl3", name: "Kids Haircut (Under 12)", durationMin: 30, price: 250, category: "grooming" },
      { id: "sl4", name: "Hair Wash & Blowdry", durationMin: 40, price: 350, category: "hair" },
      { id: "sl5", name: "Flat Iron Styling", durationMin: 30, price: 400, category: "hair" },
    ],
  },

  // ── Andheri ─────────────────────────────────────────────────────────────────
  {
    id: "lotus-spa-andheri",
    name: "Lotus Spa & Salon",
    area: "Andheri East",
    address: "MIDC Road, Andheri East, Mumbai 400093",
    lat: 19.1136, lng: 72.8697,
    phone: "+919812345678",
    whatsapp: "919812345678",
    email: "book@lotusspa.in",
    rating: 4.6, reviewCount: 189,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.spa, IMG.salon],
    tags: ["Spa", "Facial", "Skin", "Relaxation", "Home Service"],
    openHours: "9:00 AM – 8:30 PM",
    homeService: true,
    amenities: ["Home Service", "Steam Room", "Organic Products", "Acupressure"],
    description: "Andheri's beloved spa sanctuary. Our certified therapists bring the spa experience to you — at home or at our studio.",
    established: 2017,
    specialization: "Home Spa Services",
    services: [
      { id: "ls1", name: "Facial Glow", durationMin: 45, price: 899, category: "skin" },
      { id: "ls2", name: "Manicure & Pedicure", durationMin: 75, price: 1299, category: "nails" },
      { id: "ls3", name: "Full Body Massage", durationMin: 60, price: 1999, category: "spa" },
      { id: "ls4", name: "At-Home Facial", durationMin: 60, price: 1499, category: "skin" },
      { id: "ls5", name: "Organic Hair Spa", durationMin: 60, price: 1100, category: "hair" },
    ],
  },
  {
    id: "color-lab-andheri",
    name: "The Color Lab",
    area: "Andheri West",
    address: "New Link Road, Versova, Andheri West, Mumbai 400053",
    lat: 19.1365, lng: 72.8280,
    phone: "+919812345679",
    email: "hello@colorlab.in",
    rating: 4.8, reviewCount: 267,
    priceLevel: 3,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.salon, IMG.beauty],
    tags: ["Color Experts", "Balayage", "Hair Art", "Premium"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Color Lab", "Tea Bar", "VIP Rooms", "AC"],
    description: "Andheri's color destination. Our color scientists create custom shades tailored to your skin tone and hair goals.",
    established: 2019,
    specialization: "Creative Hair Coloring",
    services: [
      { id: "cl1", name: "Global Hair Coloring", durationMin: 120, price: 3500, category: "hair" },
      { id: "cl2", name: "Balayage Masterclass", durationMin: 180, price: 6000, category: "hair" },
      { id: "cl3", name: "Highlights (Foil)", durationMin: 150, price: 4500, category: "hair" },
      { id: "cl4", name: "Vivid Fashion Colors", durationMin: 180, price: 7000, category: "hair" },
      { id: "cl5", name: "Root Touch-up", durationMin: 60, price: 1800, category: "hair" },
    ],
  },
  {
    id: "groom-hub-andheri",
    name: "The Groom Hub",
    area: "Andheri East",
    address: "Saki Naka, Andheri East, Mumbai 400072",
    lat: 19.1050, lng: 72.8680,
    phone: "+919812345680",
    rating: 4.3, reviewCount: 145,
    priceLevel: 1,
    image: IMG.grooming,
    gallery: [IMG.grooming, IMG.salon],
    tags: ["Men Only", "Beard", "Quick", "Budget"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: true,
    amenities: ["Men Only", "Express Cuts", "Beard Sculpting", "Hot Towel"],
    description: "Andheri's go-to salon for the modern man. Sharp cuts, perfect beards, and zero judgment.",
    established: 2021,
    specialization: "Men's Grooming",
    services: [
      { id: "gh1", name: "Premium Haircut", durationMin: 45, price: 450, category: "grooming" },
      { id: "gh2", name: "Beard Sculpt & Trim", durationMin: 30, price: 350, category: "grooming" },
      { id: "gh3", name: "Hot Towel Shave", durationMin: 40, price: 500, category: "grooming" },
      { id: "gh4", name: "Hair + Beard Combo", durationMin: 60, price: 650, category: "grooming" },
      { id: "gh5", name: "Facial for Men", durationMin: 45, price: 700, category: "skin" },
    ],
  },
  {
    id: "gloss-andheri",
    name: "Gloss Beauty Studio",
    area: "Andheri West",
    address: "Lokhandwala, Andheri West, Mumbai 400053",
    lat: 19.1390, lng: 72.8320,
    phone: "+919812345681",
    rating: 4.5, reviewCount: 178,
    priceLevel: 2,
    image: IMG.nails,
    gallery: [IMG.nails, IMG.beauty, IMG.salon],
    tags: ["Nails", "Makeup", "Sculpture", "Acrylic"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Nail Art Studio", "Private Rooms", "AC"],
    description: "Your nail art destination in Andheri. From classic French tips to intricate nail art designs — we do it all.",
    established: 2020,
    specialization: "Nail Art & Sculpting",
    services: [
      { id: "gl1", name: "Gel Manicure", durationMin: 45, price: 700, category: "nails" },
      { id: "gl2", name: "Acrylic Extensions", durationMin: 90, price: 1800, category: "nails" },
      { id: "gl3", name: "Nail Art (Per Nail)", durationMin: 15, price: 150, category: "nails" },
      { id: "gl4", name: "Full Set with Art", durationMin: 120, price: 2500, category: "nails" },
      { id: "gl5", name: "Party Makeup", durationMin: 60, price: 2200, category: "makeup" },
    ],
  },
  {
    id: "urban-touch-andheri",
    name: "Urban Touch Salon",
    area: "Andheri East",
    address: " Chakala, Andheri East, Mumbai 400099",
    lat: 19.1100, lng: 72.8650,
    phone: "+919812345682",
    rating: 4.4, reviewCount: 112,
    priceLevel: 1,
    image: IMG.salon,
    gallery: [IMG.salon, IMG.hair],
    tags: ["All-in-One", "Affordable", "Facials", "Hair"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["All Services", "Family Friendly", "Home Service"],
    description: "Complete beauty care under one roof. All services, all budgets — the neighborhood salon that does it all.",
    established: 2018,
    specialization: "Complete Beauty Services",
    services: [
      { id: "ut1", name: "Haircut & Styling", durationMin: 45, price: 400, category: "hair" },
      { id: "ut2", name: "Classic Facial", durationMin: 45, price: 600, category: "skin" },
      { id: "ut3", name: "Hair Color", durationMin: 90, price: 1500, category: "hair" },
      { id: "ut4", name: "Waxing (Full Leg)", durationMin: 30, price: 500, category: "skin" },
      { id: "ut5", name: "At-Home Haircut", durationMin: 50, price: 700, category: "hair" },
    ],
  },

  // ── Powai ────────────────────────────────────────────────────────────────────
  {
    id: "nail-bar-powai",
    name: "Nail Bar Powai",
    area: "Powai",
    address: "Hiranandani Gardens, Powai, Mumbai 400076",
    lat: 19.1197, lng: 72.905,
    phone: "+919977665544",
    whatsapp: "919977665544",
    rating: 4.5, reviewCount: 98,
    priceLevel: 1,
    image: IMG.nails,
    gallery: [IMG.nails, IMG.beauty],
    tags: ["Nails", "Affordable", "Quick", "Student Discount"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Walk-in OK", "Nail Art", "Student Discount", "AC"],
    description: "Powai's favourite nail bar. Trendy designs, fresh colors, and the kind of self-care you deserve.",
    established: 2022,
    specialization: "Trendy Nail Art",
    services: [
      { id: "nb1", name: "Gel Manicure", durationMin: 40, price: 599, category: "nails" },
      { id: "nb2", name: "Acrylic Extensions", durationMin: 90, price: 1499, category: "nails" },
      { id: "nb3", name: "Nail Art Add-on", durationMin: 20, price: 299, category: "nails" },
      { id: "nb4", name: "Pedicure (Spa)", durationMin: 60, price: 899, category: "nails" },
      { id: "nb5", name: "Dip Powder Nails", durationMin: 60, price: 1100, category: "nails" },
    ],
  },
  {
    id: "lumiere-powai",
    name: "Lumière Hair & Beauty",
    area: "Powai",
    address: "Lake Home Road, Powai, Mumbai 400076",
    lat: 19.1210, lng: 72.9080,
    phone: "+919977665545",
    email: "book@lumierepowai.in",
    rating: 4.7, reviewCount: 156,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.hair, IMG.salon],
    tags: ["Hair", "Skin", "Bridal", "Organic", "Premium"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Organic Products", "Bridal Services", "Steam", "Private Rooms"],
    description: "Where light meets beauty. Powai's most loved salon with a focus on organic products and personalized care.",
    established: 2019,
    specialization: "Organic Beauty & Bridal",
    services: [
      { id: "lm1", name: "Organic Signature Facial", durationMin: 60, price: 1500, category: "skin" },
      { id: "lm2", name: "Haircut & Blowdry", durationMin: 60, price: 900, category: "hair" },
      { id: "lm3", name: "Bridal Makeup", durationMin: 120, price: 8000, category: "bridal" },
      { id: "lm4", name: "Keratin Treatment", durationMin: 120, price: 4000, category: "hair" },
      { id: "lm5", name: "At-Home Mehendi", durationMin: 90, price: 2000, category: "bridal" },
    ],
  },
  {
    id: "serenity-spa-powai",
    name: "Serenity Wellness Spa",
    area: "Powai",
    address: "Kasarwadi, Powai, Mumbai 400076",
    lat: 19.1180, lng: 72.9100,
    phone: "+919977665546",
    rating: 4.6, reviewCount: 134,
    priceLevel: 2,
    image: IMG.spa,
    gallery: [IMG.spa, IMG.salon],
    tags: ["Spa", "Massage", "Detox", "Wellness"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: true,
    amenities: ["Steam", "Infrared Sauna", "Couple Rooms", "Detox Programs"],
    description: "Your personal wellness sanctuary. Science-backed spa treatments for body, mind and soul.",
    established: 2020,
    specialization: "Detox & Wellness",
    services: [
      { id: "sp1", name: "Detox Body Wrap", durationMin: 90, price: 2500, category: "spa" },
      { id: "sp2", name: "Swedish Massage 90min", durationMin: 90, price: 2200, category: "spa" },
      { id: "sp3", name: "Aromatherapy Session", durationMin: 60, price: 1600, category: "spa" },
      { id: "sp4", name: "Foot Spa & Reflexology", durationMin: 45, price: 900, category: "spa" },
      { id: "sp5", name: "Couple's Massage", durationMin: 90, price: 4500, category: "spa" },
    ],
  },

  // ── Colaba ───────────────────────────────────────────────────────────────────
  {
    id: "urban-groom-colaba",
    name: "Urban Groom Colaba",
    area: "Colaba",
    address: "Colaba Causeway, Near Gateway, Mumbai 400005",
    lat: 18.9067, lng: 72.8147,
    phone: "+919900112233",
    whatsapp: "919900112233",
    rating: 4.7, reviewCount: 156,
    priceLevel: 2,
    image: IMG.grooming,
    gallery: [IMG.grooming, IMG.salon],
    tags: ["Men", "Grooming", "Beard", "Express"],
    openHours: "11:00 AM – 10:00 PM",
    homeService: false,
    amenities: ["Men Only", "Hot Towel Shave", "Express Cuts", "AC"],
    description: "Colaba's premier men's grooming destination. Old-school charm meets modern techniques.",
    established: 2018,
    specialization: "Classic Men's Grooming",
    services: [
      { id: "ug1", name: "Premium Haircut", durationMin: 45, price: 699, category: "grooming" },
      { id: "ug2", name: "Beard Sculpt & Trim", durationMin: 30, price: 499, category: "grooming" },
      { id: "ug3", name: "Head Massage + Shave", durationMin: 40, price: 599, category: "grooming" },
      { id: "ug4", name: "Clean Shave (Hot Towel)", durationMin: 30, price: 450, category: "grooming" },
      { id: "ug5", name: "Men's Facial", durationMin: 45, price: 800, category: "skin" },
    ],
  },
  {
    id: "the-hair-port-colaba",
    name: "The Hair Port",
    area: "Colaba",
    address: "Mahatma Gandhi Road, Colaba, Mumbai 400005",
    lat: 18.9080, lng: 72.8160,
    phone: "+919900112234",
    email: "book@hairport.co.in",
    rating: 4.5, reviewCount: 89,
    priceLevel: 2,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.salon, IMG.beauty],
    tags: ["Hair", "Styling", "Color", "Makeup"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["AC", "VIP Styling", "Tea Service"],
    description: "Colaba's creative hair hub. From bold cuts to stunning color — express yourself authentically.",
    established: 2020,
    specialization: "Creative Hair Styling",
    services: [
      { id: "th1", name: "Creative Haircut", durationMin: 60, price: 800, category: "hair" },
      { id: "th2", name: "Global Coloring", durationMin: 120, price: 3000, category: "hair" },
      { id: "th3", name: "Blowout & Style", durationMin: 45, price: 600, category: "hair" },
      { id: "th4", name: "Occasion Styling", durationMin: 60, price: 1200, category: "hair" },
      { id: "th5", name: "Bridal Hair Styling", durationMin: 90, price: 4500, category: "hair" },
    ],
  },

  // ── South Mumbai ─────────────────────────────────────────────────────────────
  {
    id: "taj-salon-south",
    name: "Taj Beauty Lounge",
    area: "Fort",
    address: "Hamstreet, Fort, Mumbai 400001",
    lat: 18.9325, lng: 72.8340,
    phone: "+919988112233",
    email: "info@tajbeauty.in",
    rating: 4.8, reviewCount: 234,
    priceLevel: 3,
    image: IMG.luxury,
    gallery: [IMG.luxury, IMG.salon, IMG.bridal],
    tags: ["Luxury", "Premium", "Bridal", "Corporate"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Luxury Interior", "Private Suites", "Corporate Accounts", "Valet"],
    description: "Fort's luxury beauty destination for the working professional. Corporate accounts welcome.",
    established: 2016,
    specialization: "Corporate Beauty & Luxury Treatments",
    services: [
      { id: "ts1", name: "Executive Haircut", durationMin: 45, price: 1200, category: "hair" },
      { id: "ts2", name: "Executive Facial", durationMin: 60, price: 2000, category: "skin" },
      { id: "ts3", name: "Bridal Makeup (Premium)", durationMin: 120, price: 12000, category: "bridal" },
      { id: "ts4", name: "Hair Spa Luxury", durationMin: 75, price: 1800, category: "hair" },
      { id: "ts5", name: "Manicure (Spa)", durationMin: 45, price: 1000, category: "nails" },
    ],
  },
  {
    id: "babul-house-dadar",
    name: "Babul House of Beauty",
    area: "Dadar",
    address: "Shivaji Park, Dadar West, Mumbai 400028",
    lat: 19.0150, lng: 72.8330,
    phone: "+919988112234",
    rating: 4.6, reviewCount: 178,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.hair, IMG.salon],
    tags: ["Traditional", "Mehendi", "Bridal", "Heritage"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Traditional Mehendi", "Bridal Package", "Home Service", "AC"],
    description: "Mumbai's heritage beauty house with roots in traditional Indian beauty rituals. Specializing in bridal Mehendi and wedding glam.",
    established: 2010,
    specialization: "Traditional Indian Bridal Beauty",
    services: [
      { id: "bh1", name: "Bridal Mehendi (Full)", durationMin: 180, price: 4000, category: "bridal" },
      { id: "bh2", name: "Bridal Makeup", durationMin: 120, price: 9000, category: "bridal" },
      { id: "bh3", name: "Haldi Ceremony Package", durationMin: 60, price: 3000, category: "bridal" },
      { id: "bh4", name: "Hair Styling", durationMin: 45, price: 800, category: "hair" },
      { id: "bh5", name: "Skin Glow Facial", durationMin: 60, price: 1100, category: "skin" },
    ],
  },
  {
    id: "silk-road-lower-parel",
    name: "Silk Road Beauty",
    area: "Lower Parel",
    address: "Peninsula Corporate Park, Lower Parel, Mumbai 400013",
    lat: 18.9960, lng: 72.8250,
    phone: "+919988112235",
    email: "hello@silkroadbeauty.in",
    rating: 4.7, reviewCount: 145,
    priceLevel: 3,
    image: IMG.premium,
    gallery: [IMG.premium, IMG.salon, IMG.spa],
    tags: ["Premium", "Corporate", "Anti-Aging", "Luxury Spa"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Anti-Aging Treatments", "IV Therapy", "Premium Skincare", "Executive"],
    description: "Lower Parel's exclusive beauty destination for working professionals. Science-backed anti-aging and wellness treatments.",
    established: 2021,
    specialization: "Anti-Aging & Executive Wellness",
    services: [
      { id: "sr1", name: "Botanical Anti-Aging Facial", durationMin: 75, price: 3500, category: "skin" },
      { id: "sr2", name: "LED Light Therapy", durationMin: 45, price: 2500, category: "skin" },
      { id: "sr3", name: "IV Beauty Drip", durationMin: 60, price: 5000, category: "spa" },
      { id: "sr4", name: "Lymphatic Drainage Massage", durationMin: 60, price: 3000, category: "spa" },
      { id: "sr5", name: "Microneedling Session", durationMin: 90, price: 6000, category: "skin" },
    ],
  },

  // ── Thane ────────────────────────────────────────────────────────────────────
  {
    id: "home-glam-thane",
    name: "Home Glam Thane",
    area: "Thane West",
    address: "Ghodbunder Road, Thane West, Mumbai 400607",
    lat: 19.2183, lng: 72.9781,
    phone: "+919988776655",
    whatsapp: "919988776655",
    email: "book@homeglam.in",
    rating: 4.4, reviewCount: 76,
    priceLevel: 2,
    image: IMG.salon,
    gallery: [IMG.salon, IMG.beauty],
    tags: ["Home Service", "Hair", "Skin", "Doorstep"],
    openHours: "8:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["100% Home Service", "Sanitized Kit", "Same-Day Slots", "AC Van"],
    description: "Thane's favorite home beauty service. Premium treatments delivered to your doorstep — sanitized, professional, and punctual.",
    established: 2022,
    specialization: "At-Home Premium Beauty",
    services: [
      { id: "hg1", name: "At-Home Haircut", durationMin: 50, price: 799, category: "hair" },
      { id: "hg2", name: "At-Home Facial", durationMin: 60, price: 999, category: "skin" },
      { id: "hg3", name: "Party Makeup at Home", durationMin: 75, price: 2500, category: "makeup" },
      { id: "hg4", name: "At-Home Hair Spa", durationMin: 60, price: 1200, category: "hair" },
      { id: "hg5", name: "At-Home Manicure", durationMin: 45, price: 899, category: "nails" },
    ],
  },
  {
    id: "radiant-glow-thane",
    name: "Radiant Glow Skin Clinic",
    area: "Thane West",
    address: "Vasant Vihar, Thane West, Mumbai 400607",
    lat: 19.2200, lng: 72.9750,
    phone: "+919988776656",
    email: "book@radiantglow.in",
    rating: 4.6, reviewCount: 123,
    priceLevel: 2,
    image: IMG.spa,
    gallery: [IMG.spa, IMG.salon, IMG.beauty],
    tags: ["Skin Clinic", "Acne", "Chemical Peels", "Laser"],
    openHours: "10:00 AM – 7:00 PM",
    homeService: false,
    amenities: ["Derma Clinic", "Laser Equipment", "Consultation", "Prescription Skincare"],
    description: "Thane's leading skin clinic with certified dermatologists. Clinical treatments for acne, pigmentation, and anti-aging.",
    established: 2019,
    specialization: "Clinical Dermatology & Skin Treatments",
    services: [
      { id: "rg1", name: "Skin Consultation", durationMin: 30, price: 500, category: "skin" },
      { id: "rg2", name: "HydraFacial", durationMin: 60, price: 2500, category: "skin" },
      { id: "rg3", name: "Chemical Peel", durationMin: 45, price: 2000, category: "skin" },
      { id: "rg4", name: "Acne Treatment", durationMin: 60, price: 1800, category: "skin" },
      { id: "rg5", name: "Pigmentation Reduction", durationMin: 75, price: 3000, category: "skin" },
    ],
  },
  {
    id: "style-studio-thane",
    name: "Style Studio Thane",
    area: "Thane East",
    address: "Kopeswar Road, Thane East, Mumbai 400603",
    lat: 19.1850, lng: 72.9650,
    phone: "+919988776657",
    rating: 4.3, reviewCount: 89,
    priceLevel: 1,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.salon],
    tags: ["Hair", "Budget", "Family", "Color"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["All Ages", "Budget Friendly", "Home Service", "AC"],
    description: "Thane's best-kept beauty secret. Quality cuts, colors and styling at prices that make sense.",
    established: 2021,
    specialization: "Affordable Hair Transformation",
    services: [
      { id: "ss1", name: "Haircut & Blowdry", durationMin: 50, price: 400, category: "hair" },
      { id: "ss2", name: "Hair Coloring", durationMin: 90, price: 1200, category: "hair" },
      { id: "ss3", name: "Hair rebonding", durationMin: 180, price: 3500, category: "hair" },
      { id: "ss4", name: "Keratin Treatment", durationMin: 120, price: 2800, category: "hair" },
      { id: "ss5", name: "At-Home Styling", durationMin: 60, price: 800, category: "hair" },
    ],
  },

  // ── Malad / Goregaon ─────────────────────────────────────────────────────────
  {
    id: "bliss-nail-bar-malad",
    name: "Bliss Nail Bar",
    area: "Malad West",
    address: "Infinity Mall, Malad West, Mumbai 400064",
    lat: 19.1870, lng: 72.8380,
    phone: "+919922334455",
    rating: 4.5, reviewCount: 67,
    priceLevel: 2,
    image: IMG.nails,
    gallery: [IMG.nails, IMG.beauty],
    tags: ["Nails", "Art", "Spa", "Trendy"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: false,
    amenities: ["Mall Location", "Walk-in OK", "Nail Art", "Spa Pedicure"],
    description: "Malad's most popular nail bar inside Infinity Mall. Perfect for a beauty day out with friends.",
    established: 2022,
    specialization: "Nail Art & Spa",
    services: [
      { id: "bn1", name: "Gel Manicure", durationMin: 45, price: 650, category: "nails" },
      { id: "bn2", name: "Spa Pedicure", durationMin: 60, price: 900, category: "nails" },
      { id: "bn3", name: "Nail Art Set", durationMin: 90, price: 1500, category: "nails" },
      { id: "bn4", name: "Acrylic Full Set", durationMin: 90, price: 1600, category: "nails" },
      { id: "bn5", name: "Nail Fix & Polish", durationMin: 20, price: 300, category: "nails" },
    ],
  },
  {
    id: "elegance-goregaon",
    name: "Elegance Hair Studio",
    area: "Goregaon West",
    address: "斯瓦arner Road, Goregaon West, Mumbai 400062",
    lat: 19.1540, lng: 72.8400,
    phone: "+919922334456",
    rating: 4.4, reviewCount: 91,
    priceLevel: 1,
    image: IMG.salon,
    gallery: [IMG.salon, IMG.hair],
    tags: ["Hair", "Affordable", "Family", "Blowdry"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Family Salon", "Home Service", "Kids Friendly", "AC"],
    description: "Goregaon's trusted neighborhood salon. Great hair at honest prices, with home service on request.",
    established: 2020,
    specialization: "Family Hair Care",
    services: [
      { id: "eg1", name: "Women's Haircut", durationMin: 45, price: 350, category: "hair" },
      { id: "eg2", name: "Men's Haircut", durationMin: 30, price: 250, category: "grooming" },
      { id: "eg3", name: "Hair Coloring", durationMin: 90, price: 1100, category: "hair" },
      { id: "eg4", name: "Hair Spa", durationMin: 60, price: 800, category: "hair" },
      { id: "eg5", name: "Blowdry Styling", durationMin: 30, price: 300, category: "hair" },
    ],
  },

  // ── Khar / Santacruz ─────────────────────────────────────────────────────────
  {
    id: "flair-salon-khar",
    name: "Flair Hair & Beauty",
    area: "Khar West",
    address: "Khar Road Station, Khar West, Mumbai 400052",
    lat: 19.0700, lng: 72.8370,
    phone: "+919933445566",
    rating: 4.6, reviewCount: 134,
    priceLevel: 2,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.beauty, IMG.salon],
    tags: ["Hair", "Balayage", "Bridal", "Styling"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Expert Stylists", "Bridal Services", "Home Service", "AC"],
    description: "Khar's rising star in beauty. Our young team brings fresh ideas and modern techniques to every appointment.",
    established: 2021,
    specialization: "Modern Hair Styling",
    services: [
      { id: "fs1", name: "Precision Haircut", durationMin: 45, price: 700, category: "hair" },
      { id: "fs2", name: "Balayage Highlights", durationMin: 150, price: 5000, category: "hair" },
      { id: "fs3", name: "Bridal Hair Styling", durationMin: 90, price: 4000, category: "hair" },
      { id: "fs4", name: "Hair Coloring", durationMin: 90, price: 2500, category: "hair" },
      { id: "fs5", name: "At-Home Hair Styling", durationMin: 60, price: 1500, category: "hair" },
    ],
  },
  {
    id: "glow-up-santacruz",
    name: "Glow Up Beauty Bar",
    area: "Santacruz West",
    address: "Sardar Patel Road, Santacruz West, Mumbai 400054",
    lat: 19.0770, lng: 72.8380,
    phone: "+919933445567",
    email: "hello@glowupbeauty.in",
    rating: 4.5, reviewCount: 112,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.salon, IMG.nails],
    tags: ["Makeup", "Skin", "Brows", "Lashes"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Makeup Artists", "Brow Bar", "Lash Studio", "Home Service"],
    description: "Where every client glows up. Santacruz's go-to for makeup, skin care, and brow artistry.",
    established: 2020,
    specialization: "Makeup & Brow Artistry",
    services: [
      { id: "gu1", name: "HD Party Makeup", durationMin: 60, price: 2000, category: "makeup" },
      { id: "gu2", name: "Bridal Makeup Trial", durationMin: 90, price: 3000, category: "bridal" },
      { id: "gu3", name: "Brow Lamination", durationMin: 45, price: 1100, category: "grooming" },
      { id: "gu4", name: "Lash Lift", durationMin: 60, price: 1500, category: "grooming" },
      { id: "gu5", name: "Facial Glow", durationMin: 60, price: 1100, category: "skin" },
    ],
  },

  // ── Versova / Lokhandwala ────────────────────────────────────────────────────
  {
    id: "bare-beauty-versova",
    name: "Bare Beauty Studio",
    area: "Versova",
    address: "7th Cross Lane, Versova, Andheri West, Mumbai 400061",
    lat: 19.1340, lng: 72.8230,
    phone: "+919944556677",
    email: "bare@beautyversova.in",
    rating: 4.7, reviewCount: 189,
    priceLevel: 2,
    image: IMG.spa,
    gallery: [IMG.spa, IMG.salon, IMG.beauty],
    tags: ["Clean Beauty", "Organic", "Minimalist", "Skin"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: false,
    amenities: ["Organic Only", "Clean Beauty", "Zero-Waste", "Expert Facials"],
    description: "Clean, conscious beauty for the modern woman. We use only certified organic products for skin and hair treatments.",
    established: 2021,
    specialization: "Organic Clean Beauty",
    services: [
      { id: "bb1", name: "Organic Glow Facial", durationMin: 60, price: 1500, category: "skin" },
      { id: "bb2", name: "Ayurvedic Head Massage", durationMin: 45, price: 900, category: "hair" },
      { id: "bb3", name: "Clean Beauty Makeup", durationMin: 60, price: 2500, category: "makeup" },
      { id: "bb4", name: "Herbal Body Wrap", durationMin: 75, price: 2000, category: "spa" },
      { id: "bb5", name: "Natural Brow Shape", durationMin: 30, price: 500, category: "grooming" },
    ],
  },
  {
    id: "velvet-salon-versova",
    name: "Velvet Hair Salon",
    area: "Versova",
    address: "Inorbit Mall, Versova, Andheri West, Mumbai 400061",
    lat: 19.1360, lng: 72.8210,
    phone: "+919944556678",
    rating: 4.6, reviewCount: 145,
    priceLevel: 3,
    image: IMG.luxury,
    gallery: [IMG.luxury, IMG.hair, IMG.salon],
    tags: ["Hair Art", "Luxury", "Celebrity", "Trends"],
    openHours: "10:00 AM – 9:00 PM",
    homeService: false,
    amenities: ["Mall Location", "Celebrity Stylists", "Trend Hub", "VIP Rooms"],
    description: "Versova's celebrity salon. Featured on Instagram for our trend-forward styles and stunning transformations.",
    established: 2019,
    specialization: "Celebrity Hair Styling",
    services: [
      { id: "vs1", name: "Celebrity Haircut", durationMin: 60, price: 1500, category: "hair" },
      { id: "vs2", name: "Viral Hair Trends", durationMin: 150, price: 6000, category: "hair" },
      { id: "vs3", name: "Color Correction", durationMin: 240, price: 10000, category: "hair" },
      { id: "vs4", name: "Brazilian Keratin", durationMin: 180, price: 7000, category: "hair" },
      { id: "vs5", name: "Root Smudge", durationMin: 120, price: 4500, category: "hair" },
    ],
  },

  // ── Mira Road / Bhayandar ───────────────────────────────────────────────────
  {
    id: "sparkle-mira-road",
    name: "Sparkle Beauty Lounge",
    area: "Mira Road",
    address: "Mira Bhayandar Road, Near Station, Mira Road, Mumbai 401107",
    lat: 19.2812, lng: 72.8677,
    phone: "+919955667788",
    rating: 4.4, reviewCount: 78,
    priceLevel: 1,
    image: IMG.salon,
    gallery: [IMG.salon, IMG.beauty],
    tags: ["Budget", "Family", "All Services", "Convenient"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Station Area", "Home Service", "Family Packages", "AC"],
    description: "Mira Road's most convenient full-service salon. Everything you need, right near the station, at prices that make sense.",
    established: 2022,
    specialization: "Convenient Family Beauty",
    services: [
      { id: "sp1", name: "Haircut & Blowdry", durationMin: 45, price: 350, category: "hair" },
      { id: "sp2", name: "Facial Clean-up", durationMin: 45, price: 500, category: "skin" },
      { id: "sp3", name: "Hair Color", durationMin: 90, price: 1000, category: "hair" },
      { id: "sp4", name: "Waxing (Full Arms)", durationMin: 30, price: 400, category: "skin" },
      { id: "sp5", name: "Manicure", durationMin: 30, price: 350, category: "nails" },
    ],
  },

  // ── Vashi / Navi Mumbai ──────────────────────────────────────────────────────
  {
    id: "lush-navi-mumbai",
    name: "Lush Beauty Hub",
    area: "Vashi",
    address: "Sector 17, Vashi, Navi Mumbai 400703",
    lat: 19.0643, lng: 72.9997,
    phone: "+919966778899",
    email: "lush@beautyhub.in",
    rating: 4.5, reviewCount: 112,
    priceLevel: 2,
    image: IMG.beauty,
    gallery: [IMG.beauty, IMG.hair, IMG.salon],
    tags: ["Hair", "Skin", "Spa", "Bridal", "Navi Mumbai"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Complete Services", "Bridal Packages", "Home Service", "AC"],
    description: "Navi Mumbai's premier beauty destination. One-stop shop for everything from quick trims to elaborate bridal packages.",
    established: 2018,
    specialization: "Complete Beauty Services",
    services: [
      { id: "lh1", name: "Hair Styling", durationMin: 60, price: 800, category: "hair" },
      { id: "lh2", name: "Bridal Makeup", durationMin: 120, price: 8000, category: "bridal" },
      { id: "lh3", name: "Spa Massage 60min", durationMin: 60, price: 1800, category: "spa" },
      { id: "lh4", name: "Signature Facial", durationMin: 60, price: 1200, category: "skin" },
      { id: "lh5", name: "Nail Art Combo", durationMin: 60, price: 1000, category: "nails" },
    ],
  },

  // ── Kurla / Chembur ──────────────────────────────────────────────────────────
  {
    id: "pretty-me-kurla",
    name: "Pretty Me Salon & Spa",
    area: "Kurla West",
    address: "LBS Road, Kurla West, Mumbai 400070",
    lat: 19.0720, lng: 72.8770,
    phone: "+919977889900",
    rating: 4.3, reviewCount: 67,
    priceLevel: 1,
    image: IMG.nails,
    gallery: [IMG.nails, IMG.beauty],
    tags: ["Nails", "Skin", "Affordable", "Quick"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Affordable", "Home Service", "Walk-in OK", "Quick Turnaround"],
    description: "Kurla's most loved beauty spot for nails and skin. Fast, affordable, and always stylish.",
    established: 2023,
    specialization: "Nails & Quick Skin Care",
    services: [
      { id: "pm1", name: "Gel Manicure", durationMin: 40, price: 550, category: "nails" },
      { id: "pm2", name: "Facial Clean-up", durationMin: 45, price: 500, category: "skin" },
      { id: "pm3", name: "Pedicure", durationMin: 50, price: 700, category: "nails" },
      { id: "pm4", name: "Threading Package", durationMin: 20, price: 250, category: "grooming" },
      { id: "pm5", name: "At-Home Facial", durationMin: 60, price: 900, category: "skin" },
    ],
  },
  {
    id: "aura-chembur",
    name: "Aura Beauty Studio",
    area: "Chembur",
    address: "Tilak Nagar, Chembur, Mumbai 400089",
    lat: 19.0520, lng: 72.8920,
    phone: "+919977889901",
    email: "aura@beauty.in",
    rating: 4.6, reviewCount: 98,
    priceLevel: 2,
    image: IMG.hair,
    gallery: [IMG.hair, IMG.salon, IMG.beauty],
    tags: ["Hair Experts", "Color", "Smoothing", "Home Service"],
    openHours: "9:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Hair Color Lab", "Keratin", "Home Service", "AC"],
    description: "Chembur's finest hair studio. Expert colorists and smoothing treatments at neighborhood prices.",
    established: 2020,
    specialization: "Hair Color & Smoothing",
    services: [
      { id: "ac1", name: "Haircut & Blowdry", durationMin: 50, price: 500, category: "hair" },
      { id: "ac2", name: "Global Hair Coloring", durationMin: 120, price: 2000, category: "hair" },
      { id: "ac3", name: "Keratin Treatment", durationMin: 120, price: 3500, category: "hair" },
      { id: "ac4", name: "Balayage", durationMin: 150, price: 4000, category: "hair" },
      { id: "ac5", name: "At-Home Hair Service", durationMin: 60, price: 1000, category: "hair" },
    ],
  },

  // ── Mulund ───────────────────────────────────────────────────────────────────
  {
    id: "bloom-multiple",
    name: "Bloom Beauty & Wellness",
    area: "Mulund West",
    address: "LBS Road, Mulund West, Mumbai 400080",
    lat: 19.1720, lng: 72.9200,
    phone: "+919988990011",
    rating: 4.5, reviewCount: 134,
    priceLevel: 2,
    image: IMG.spa,
    gallery: [IMG.spa, IMG.beauty, IMG.salon],
    tags: ["Spa", "Wellness", "Skin", "Relaxation", "Home Service"],
    openHours: "10:00 AM – 8:00 PM",
    homeService: true,
    amenities: ["Spa Treatments", "Home Service", "Couple Rooms", "Steam"],
    description: "Mulund's wellness oasis. Escape the city stress with our curated spa and skin treatments.",
    established: 2021,
    specialization: "Wellness & Relaxation",
    services: [
      { id: "bm1", name: "Swedish Massage", durationMin: 60, price: 1500, category: "spa" },
      { id: "bm2", name: "Deep Tissue Therapy", durationMin: 75, price: 2000, category: "spa" },
      { id: "bm3", name: "HydraFacial", durationMin: 60, price: 2500, category: "skin" },
      { id: "bm4", name: "Body Scrub Ritual", durationMin: 60, price: 1800, category: "spa" },
      { id: "bm5", name: "Couple's Spa Day", durationMin: 120, price: 4000, category: "spa" },
    ],
  },
];

export function getSalonById(id: string): Salon | undefined {
  return SALONS.find((s) => s.id === id);
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function priceLevelLabel(level: 1 | 2 | 3): string {
  return "₹".repeat(level) + "·".repeat(3 - level);
}

export const AREAS = [
  "All Areas",
  "Bandra West",
  "Juhu",
  "Andheri West",
  "Andheri East",
  "Powai",
  "Colaba",
  "Fort",
  "Dadar",
  "Lower Parel",
  "Thane West",
  "Thane East",
  "Malad West",
  "Goregaon West",
  "Khar West",
  "Santacruz West",
  "Versova",
  "Mira Road",
  "Vashi",
  "Kurla West",
  "Chembur",
  "Mulund West",
] as const;

export const SERVICE_CATEGORIES = [
  { value: "all", label: "All Services" },
  { value: "hair", label: "💇 Hair" },
  { value: "skin", label: "✨ Skin & Facials" },
  { value: "nails", label: "💅 Nails" },
  { value: "bridal", label: "👰 Bridal" },
  { value: "grooming", label: "🧔 Grooming" },
  { value: "spa", label: "🧖 Spa & Wellness" },
  { value: "makeup", label: "💄 Makeup" },
] as const;