"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import {
  generateOccasionPlan,
  getOccasionConfig,
  ALL_OCCASIONS,
} from "@/lib/ai-occasion-planner";
import type { OccasionPlan } from "@/lib/types";

export default function OccasionPlannerPage() {
  const [selectedOccasion, setSelectedOccasion] = useState<string>("wedding");
  const [selectedSub, setSelectedSub] = useState<string>("");
  const [plan, setPlan] = useState<OccasionPlan | null>(null);
  const [loading, setLoading] = useState(false);

  const config = getOccasionConfig(selectedOccasion);

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setPlan(null);
    try {
      const result = await generateOccasionPlan(
        selectedOccasion as import("@/lib/types").Occasion,
        selectedSub || undefined
      );
      setPlan(result);
    } finally {
      setLoading(false);
    }
  }, [selectedOccasion, selectedSub]);

  return (
    <div className="min-h-screen py-14 px-4 sm:px-6">
      <div className="mx-auto max-w-5xl">
        {/* Header */}
        <div className="text-center mb-14">
          <span className="inline-flex items-center gap-2 rounded-full bg-violet-soft border border-violet/20 px-5 py-2 text-sm font-semibold text-violet mb-6">
            🗓️ AI-Powered · Day-by-Day Planning
          </span>
          <h1 className="font-display text-4xl font-bold text-foreground sm:text-5xl lg:text-6xl tracking-tight">
            AI Occasion{" "}
            <span className="gradient-text-bright">Planner</span>
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-muted leading-relaxed">
            From weddings to interviews — get a complete day-by-day beauty preparation timeline,
            service plan, and salon recommendations generated by AI.
          </p>
        </div>

        {/* ── Selection ─────────────────────────────────────────────────────── */}
        <div className="glass-card rounded-3xl p-8 sm:p-10 mb-10">
          {/* Occasion grid */}
          <div className="mb-8">
            <label className="block mb-4">
              <span className="font-display text-sm font-semibold text-foreground flex items-center gap-2">
                <span>🗓️</span> What&apos;re you preparing for?
              </span>
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
              {ALL_OCCASIONS.map((occ) => (
                <button
                  key={occ.value}
                  type="button"
                  onClick={() => {
                    setSelectedOccasion(occ.value);
                    setSelectedSub("");
                    setPlan(null);
                  }}
                  className={`rounded-2xl p-4 text-center transition-all ${
                    selectedOccasion === occ.value
                      ? "bg-gradient-to-br from-blush/20 to-violet/10 border-2 border-blush/40 text-blush"
                      : "border border-border text-muted hover:border-blush/30 hover:text-foreground"
                  }`}
                >
                  <div className="text-3xl mb-2">{occ.icon}</div>
                  <p className="text-xs font-semibold leading-tight">{occ.label}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Sub-occasion */}
          {config.subOccasions.length > 0 && (
            <div className="mb-8">
              <label className="block mb-4">
                <span className="font-display text-sm font-semibold text-foreground flex items-center gap-2">
                  <span>✨</span> Specific type (optional)
                </span>
              </label>
              <div className="flex flex-wrap gap-2">
                {config.subOccasions.map((sub) => (
                  <button
                    key={sub}
                    type="button"
                    onClick={() => setSelectedSub(sub === selectedSub ? "" : sub)}
                    className={`rounded-full px-4 py-2 text-xs font-semibold transition-all ${
                      selectedSub === sub
                        ? "bg-violet/20 text-violet border border-violet/30"
                        : "border border-border text-muted hover:border-violet/30 hover:text-foreground"
                    }`}
                  >
                    {sub}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Generate button */}
          <div className="flex items-center gap-4">
            <button
              type="button"
              onClick={handleGenerate}
              disabled={loading}
              className="rounded-2xl bg-gradient-to-r from-violet to-blush px-8 py-4 text-sm font-semibold text-white shadow-lg transition-all hover:opacity-90 active:scale-95 disabled:opacity-60 flex items-center gap-2"
            >
              {loading ? (
                <>
                  <span className="text-lg animate-spin">⚙️</span>
                  <span>Generating your plan...</span>
                </>
              ) : (
                <>
                  <span>🗓️</span>
                  <span>Generate My Occasion Plan</span>
                </>
              )}
            </button>
            <div className="text-sm text-muted">
              <span className="font-semibold text-foreground">{config.preparationDays}</span> days prep
              ·{" "}
              <span className="font-semibold text-foreground capitalize">{config.difficulty}</span>{" "}
              difficulty
            </div>
          </div>
        </div>

        {/* ── Loading ───────────────────────────────────────────────────────── */}
        {loading && (
          <div className="glass-card rounded-3xl p-12 text-center">
            <div className="mx-auto mb-6 h-20 w-20 rounded-full bg-violet-soft flex items-center justify-center">
              <div className="text-4xl animate-bounce">🤖</div>
            </div>
            <h2 className="font-display text-xl font-bold text-foreground">AI is building your timeline...</h2>
            <p className="mt-3 text-muted">Creating personalized day-by-day preparation plan</p>
          </div>
        )}

        {/* ── Plan Results ──────────────────────────────────────────────────── */}
        {!loading && plan && (
          <div className="anim-fade-up space-y-8">
            {/* Overview */}
            <div className="glass-card rounded-3xl p-8">
              <div className="flex items-start gap-4 mb-6">
                <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet to-blush text-3xl shadow-lg">
                  {config.icon}
                </div>
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <span className="rounded-full bg-violet-soft px-3 py-1 text-xs font-semibold text-violet">
                      {plan.difficulty} prep
                    </span>
                    <span className="rounded-full bg-blush-soft px-3 py-1 text-xs font-semibold text-blush">
                      {plan.preparationDays} days
                    </span>
                    <span className="rounded-full bg-gold-soft px-3 py-1 text-xs font-semibold text-gold">
                      Est. {plan.estimatedTotalBudget}
                    </span>
                  </div>
                  <h2 className="font-display text-2xl font-bold text-foreground">
                    {plan.occasion}
                    {plan.subOccasion && (
                      <span className="text-muted font-normal"> · {plan.subOccasion}</span>
                    )}{" "}
                    Preparation Plan
                  </h2>
                  <p className="mt-2 text-muted">
                    AI-generated timeline with services, tips, and salon recommendations
                  </p>
                </div>
              </div>
            </div>

            {/* Timeline */}
            <div>
              <h3 className="font-display text-xl font-bold text-foreground mb-1">
                Your Day-by-Day Timeline
              </h3>
              <p className="text-sm text-muted mb-6">
                Follow this plan for the best results on your big day
              </p>
              <div className="relative">
                {/* Vertical line */}
                <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-gradient-to-b from-blush via-violet to-gold opacity-30" />

                <div className="space-y-4">
                  {plan.timeline.map((step, i) => (
                    <div key={i} className="relative flex gap-6">
                      {/* Dot */}
                      <div className="relative z-10 flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blush to-violet text-lg shadow-lg">
                        {step.icon}
                      </div>
                      {/* Content */}
                      <div className="flex-1 glass-light rounded-2xl border border-border p-5 mb-2">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="rounded-full bg-emerald/20 px-2.5 py-0.5 text-[10px] font-semibold text-emerald">
                            {step.daysBefore === 0 ? "Today" : `${step.daysBefore} days before`}
                          </span>
                        </div>
                        <h4 className="font-display text-base font-semibold text-foreground mb-2">
                          {step.title}
                        </h4>
                        <p className="text-sm text-muted leading-relaxed mb-3">{step.description}</p>
                        <div className="flex flex-wrap gap-2 mb-3">
                          {step.services.map((svc) => (
                            <span key={svc} className="rounded-full bg-surface-3 px-3 py-1 text-xs text-muted">
                              {svc}
                            </span>
                          ))}
                        </div>
                        <div className="rounded-xl bg-blush-soft/30 border border-blush/10 p-3">
                          <p className="text-xs text-blush font-semibold mb-1">💡 Pro tip</p>
                          <p className="text-xs text-muted">{step.tip}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Do's and Don'ts */}
            <div className="grid gap-6 lg:grid-cols-2">
              <div className="glass-card rounded-2xl p-6">
                <h3 className="font-display text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <span className="text-2xl">✅</span> Do&apos;s
                </h3>
                <ul className="space-y-3">
                  {plan.dos.map((item, i) => (
                    <li key={i} className="flex items-start gap-3 text-sm text-muted">
                      <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald/20 text-emerald text-[10px]">✓</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="glass-card rounded-2xl p-6">
                <h3 className="font-display text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <span className="text-2xl">❌</span> Don&apos;ts
                </h3>
                <ul className="space-y-3">
                  {plan.donts.map((item, i) => (
                    <li key={i} className="flex items-start gap-3 text-sm text-muted">
                      <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-rose-400/20 text-rose-400 text-[10px]">✕</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Salon recommendations */}
            <div>
              <h3 className="font-display text-xl font-bold text-foreground mb-1">
                Recommended Salons
              </h3>
              <p className="text-sm text-muted mb-6">
                AI-matched based on your occasion and preparation needs
              </p>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {plan.salonRecommendations.map((salon, i) => (
                  <div key={i} className="glass-light rounded-2xl p-5 border border-border">
                    <div className="text-2xl mb-3">🏠</div>
                    <h4 className="font-display text-sm font-semibold text-foreground mb-1">{salon.name}</h4>
                    <p className="text-xs text-muted mb-2">{salon.area} · ★ {salon.rating}</p>
                    <p className="text-xs text-blush">{salon.specialty}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Key services */}
            <div>
              <h3 className="font-display text-xl font-bold text-foreground mb-1">
                Key Services You&apos;ll Need
              </h3>
              <p className="text-sm text-muted mb-6">Services recommended for your {plan.occasion.toLowerCase()} prep</p>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {plan.keyServices.map((svc, i) => (
                  <div key={i} className="glass-light rounded-xl p-4 border border-border">
                    <p className="text-sm font-semibold text-foreground mb-1">{svc.name}</p>
                    <p className="text-xs text-muted capitalize mb-2">{svc.category}</p>
                    <p className="text-xs text-gold font-semibold">{svc.priceRange}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="glass-light rounded-2xl p-6 text-center">
              <p className="text-sm text-muted mb-4">
                Ready to book the services from your plan?
              </p>
              <div className="flex flex-wrap justify-center gap-3">
                <Link href={`/budget-optimizer`} className="rounded-xl bg-gradient-to-r from-gold to-rose-gold px-5 py-2.5 text-sm font-semibold text-white shadow-lg">
                  💰 Budget Optimizer
                </Link>
                <Link href="/#salons" className="rounded-xl border border-blush-soft bg-blush-soft px-5 py-2.5 text-sm font-semibold text-blush">
                  💅 Browse Salons
                </Link>
                <button
                  type="button"
                  onClick={() => setPlan(null)}
                  className="rounded-xl border border-border px-5 py-2.5 text-sm font-semibold text-muted hover:border-blush hover:text-blush"
                >
                  ↻ Try Another Occasion
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}