import Link from "next/link";
import { SITE_CONFIG } from "@/lib/config";
import { SALONS } from "@/lib/salons";
import { SalonExplorer } from "@/components/SalonExplorer";
import { GlamBookAIStylist } from "@/components/GlamBookAIStylist";
import { AiFinder } from "@/components/AiFinder";
import { AnimatedStats } from "@/components/AnimatedStats";

const AI_FEATURES = [
  {
    href: "/beauty-analysis",
    icon: "🔬",
    title: "AI Beauty Analysis",
    desc: "Upload a selfie. Get face shape, skin tone, hair type & personalized recommendations in 30 seconds.",
    badge: "Most Popular",
    gradient: "from-blush to-blush/60",
    glow: "shadow-glow-primary",
  },
  {
    href: "/budget-optimizer",
    icon: "💰",
    title: "AI Budget Optimizer",
    desc: "Enter your budget & occasion. Get the perfect beauty package — optimized by AI.",
    badge: "Smart Savings",
    gradient: "from-gold to-rose-gold",
    glow: "shadow-glow-secondary",
  },
  {
    href: "/occasion-planner",
    icon: "🗓️",
    title: "AI Occasion Planner",
    desc: "From weddings to interviews — get a day-by-day beauty prep timeline generated by AI.",
    badge: "Never Miss a Step",
    gradient: "from-violet to-blush",
    glow: "shadow-glow-primary",
  },
  {
    href: "/dashboard",
    icon: "📊",
    title: "Salon Owner Dashboard",
    desc: "Real-time analytics, revenue insights, customer trends & demand forecasting.",
    badge: "For Partners",
    gradient: "from-emerald to-blush",
    glow: "shadow-glow-primary",
  },
];

const WHY_GLAMBOOK = [
  {
    icon: "🧠",
    title: "AI-First Decisions",
    desc: "Not just a booking app — an intelligent beauty advisor that learns your preferences.",
  },
  {
    icon: "🎯",
    title: "Hyper-Personalized",
    desc: "Recommendations based on your actual face shape, skin tone, and hair profile.",
  },
  {
    icon: "⚡",
    title: "One-Tap Booking",
    desc: "From AI recommendation to confirmed appointment in under 60 seconds.",
  },
  {
    icon: "🔒",
    title: "Verified Reviews",
    desc: "Real reviews from real clients. No fakes, no paid promotions.",
  },
];

export default function HomePage() {
  return (
    <>
      {/* ── Hero Section ─────────────────────────────────────────────────── */}
      <section className="relative min-h-[95vh] flex items-center overflow-hidden">
        {/* Layered background for depth */}
        <div className="absolute inset-0">
          {/* Primary gradient orb */}
          <div className="absolute -right-40 -top-40 h-[600px] w-[600px] rounded-full bg-gradient-to-br from-blush/20 via-blush/10 to-transparent blur-[120px]" />
          {/* Secondary gradient orb */}
          <div className="absolute -left-40 bottom-0 h-[500px] w-[500px] rounded-full bg-gradient-to-tr from-rose-gold/15 via-transparent to-transparent blur-[100px]" />
          {/* Tertiary accent */}
          <div className="absolute right-1/3 bottom-1/3 h-[400px] w-[400px] rounded-full bg-gradient-to-t from-violet/10 to-transparent blur-[80px]" />
          {/* Subtle grid overlay */}
          <div
            className="absolute inset-0 opacity-[0.04]"
            style={{
              backgroundImage:
                "linear-gradient(rgba(240, 171, 252, 0.8) 1px, transparent 1px), linear-gradient(90deg, rgba(240, 171, 252, 0.8) 1px, transparent 1px)",
              backgroundSize: "80px 80px",
            }}
          />
          {/* Bottom fade */}
          <div className="absolute bottom-0 left-0 right-0 h-48 bg-gradient-to-t from-background to-transparent" />
        </div>

        <div className="relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:py-32">
          {/* Premium badge */}
          <div className="anim-fade-up mb-10 inline-flex items-center gap-3 rounded-full border border-blush-soft/50 bg-blush-soft/20 px-5 py-2 backdrop-blur-md">
            <span className="relative flex h-2.5 w-2.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-blush opacity-60" />
              <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-blush-bright" />
            </span>
            <span className="text-sm font-semibold text-foreground">{SITE_CONFIG.tagline}</span>
          </div>

          {/* Dramatic headline */}
          <div className="anim-fade-up" style={{ animationDelay: "100ms" }}>
            <h1 className="font-hero text-5xl font-bold tracking-tight sm:text-6xl lg:text-8xl leading-[1.02]">
              <span className="text-foreground">Know your look.</span>
              <br />
              <span className="gradient-text-bright text-glow">Own your beauty.</span>
            </h1>
          </div>

          {/* Value proposition - more prominent */}
          <p
            className="anim-fade-up mt-8 max-w-2xl text-xl sm:text-2xl text-muted leading-relaxed font-medium"
            style={{ animationDelay: "200ms" }}
          >
            {SITE_CONFIG.description}
          </p>

          {/* Premium CTA buttons */}
          <div
            className="anim-fade-up mt-12 flex flex-wrap items-center gap-5"
            style={{ animationDelay: "300ms" }}
          >
            <Link
              href="/beauty-analysis"
              className="group flex items-center gap-4 rounded-2xl bg-gradient-to-r from-blush via-blush-bright to-rose-gold px-8 py-5 text-lg font-bold text-white shadow-2xl shadow-blush/30 transition-all duration-300 hover:scale-105 active:scale-95 hover:shadow-glow-primary btn-glow"
            >
              <span className="text-3xl">🔬</span>
              <div>
                <p>Try AI Beauty Analysis</p>
                <p className="text-sm font-normal opacity-90">Free · 30 seconds</p>
              </div>
              <span className="ml-2 transition-transform group-hover:translate-x-1">→</span>
            </Link>
            <Link
              href="/#salons"
              className="glass-card flex items-center gap-4 rounded-2xl border border-blush/20 px-8 py-5 text-lg font-semibold text-foreground transition-all duration-300 hover:border-blush/40 hover:bg-blush-soft/20 hover:scale-105 active:scale-95"
            >
              <span className="text-3xl">💅</span>
              <p>Browse {SALONS.length} Salons</p>
            </Link>
          </div>

          {/* Stats - more impactful */}
          <div
            className="anim-fade-up mt-20 pt-8 border-t border-white/5"
            style={{ animationDelay: "400ms" }}
          >
            <AnimatedStats />
          </div>
        </div>
      </section>

      {/* ── AI Features Showcase ──────────────────────────────────────────── */}
      <section className="relative py-28 px-4 sm:px-6">
        {/* Section background glow */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-blush/5 blur-[120px] rounded-full" />
        
        <div className="relative mx-auto max-w-7xl">
          {/* Section header - more dramatic */}
          <div className="text-center mb-16">
            <span className="inline-flex items-center gap-2 rounded-full bg-blush-soft border border-blush/20 px-5 py-2 text-sm font-semibold text-blush mb-6">
              <span>🚀</span> Four AI Features. One Platform.
            </span>
            <h2 className="font-display text-4xl font-bold text-foreground sm:text-5xl lg:text-6xl tracking-tight">
              Beyond Just a{" "}
              <span className="gradient-text-bright">Salon App</span>
            </h2>
            <p className="mt-6 max-w-2xl mx-auto text-lg text-muted leading-relaxed">
              GlamBook AI transforms how you discover, decide, and book beauty services — powered
              by intelligent analysis and personalized recommendations.
            </p>
          </div>

          {/* Feature cards - premium styling */}
          <div className="grid gap-6 sm:grid-cols-2">
            {AI_FEATURES.map((feature, i) => (
              <Link
                key={feature.href}
                href={feature.href}
                className="group glass-card rounded-3xl p-8 transition-all duration-400 hover:-translate-y-2 hover:border-blush/30 hover:shadow-glow-sm"
                style={{ animationDelay: `${i * 100}ms` }}
              >
                <div className="flex items-start gap-6">
                  <div
                    className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br ${feature.gradient} text-3xl shadow-lg ${feature.glow}`}
                  >
                    {feature.icon}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="font-display text-xl font-bold text-foreground group-hover:text-blush transition-colors duration-300">
                        {feature.title}
                      </h3>
                      <span className="rounded-full bg-gold-soft border border-gold/20 px-3 py-1 text-xs font-bold text-gold">
                        {feature.badge}
                      </span>
                    </div>
                    <p className="text-base text-muted leading-relaxed">{feature.desc}</p>
                    <div className="mt-5 flex items-center gap-2 text-sm font-semibold text-blush">
                      <span>Explore feature</span>
                      <span className="transition-transform group-hover:translate-x-2">→</span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── AI Beauty Analysis Preview ────────────────────────────────────── */}
      <section className="relative py-28 px-4 sm:px-6">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-blush/3 to-transparent" />
        <div className="relative mx-auto max-w-7xl">
          <div className="glass-card rounded-3xl overflow-hidden">
            <div className="grid lg:grid-cols-2">
              {/* Left: Content */}
              <div className="p-12 sm:p-16 flex flex-col justify-center">
                <span className="inline-flex items-center gap-2 rounded-full bg-blush-soft border border-blush/20 px-4 py-2 text-sm font-semibold text-blush mb-6 w-fit">
                  🔬 AI-Powered · Real Analysis
                </span>
                <h2 className="font-display text-4xl font-bold text-foreground sm:text-5xl leading-tight tracking-tight">
                  Your face tells a story.
                  <br />
                  <span className="gradient-text-bright">AI reads it perfectly.</span>
                </h2>
                <p className="mt-6 text-lg text-muted leading-relaxed">
                  Upload a selfie and our AI instantly analyzes your face shape, skin tone, hair
                  type, and condition — then generates personalized hairstyle, makeup, and grooming
                  recommendations just for you.
                </p>
                <ul className="mt-8 space-y-4">
                  {[
                    "Face shape detection with confidence score",
                    "Skin tone analysis with hex values",
                    "Hair type & condition insights",
                    "Personalized look recommendations",
                    "Matched salon recommendations",
                  ].map((item) => (
                    <li key={item} className="flex items-center gap-4 text-base text-muted">
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blush/20 text-blush text-sm font-bold">
                        ✓
                      </span>
                      {item}
                    </li>
                  ))}
                </ul>
                <div className="mt-10">
                  <Link
                    href="/beauty-analysis"
                    className="inline-flex items-center gap-3 rounded-2xl bg-gradient-to-r from-blush to-rose-gold px-8 py-4 text-lg font-bold text-white shadow-2xl shadow-blush/25 transition-all hover:scale-105 active:scale-95 hover:shadow-glow-primary"
                  >
                    🔬 Start AI Beauty Analysis — Free
                  </Link>
                </div>
              </div>

              {/* Right: Mock UI Preview */}
              <div className="relative bg-gradient-to-br from-surface-2 to-surface-3 p-10 flex items-center justify-center min-h-[500px]">
                {/* Glow effect behind */}
                <div className="absolute -inset-10 bg-gradient-to-br from-blush/15 to-rose-gold/10 blur-[60px]" />
                <div className="relative w-full max-w-sm">
                  {/* Phone frame mock - premium styling */}
                  <div className="rounded-3xl border-2 border-border/50 bg-surface overflow-hidden shadow-2xl shadow-blush/10">
                    {/* Status bar */}
                    <div className="flex items-center justify-between px-5 py-3 border-b border-border/50 bg-surface-2">
                      <div className="h-1.5 w-20 rounded-full bg-muted/30" />
                      <div className="h-4 w-4 rounded-full border-2 border-muted/30" />
                    </div>
                    {/* Content */}
                    <div className="p-5 space-y-4">
                      <div className="text-center">
                        <div className="mx-auto mb-4 h-24 w-24 rounded-full bg-gradient-to-br from-blush via-blush-bright to-rose-gold flex items-center justify-center text-4xl shadow-lg shadow-blush/30">
                          🔬
                        </div>
                        <p className="text-base font-bold text-foreground">Analyzing your selfie...</p>
                        <div className="mt-3 h-2 w-full rounded-full bg-surface-3 overflow-hidden">
                          <div className="h-full w-3/4 rounded-full bg-gradient-to-r from-blush to-rose-gold anim-shimmer" />
                        </div>
                      </div>
                      {/* Analysis results mock */}
                      <div className="glass-light rounded-xl p-4 space-y-3">
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-muted">Face Shape</span>
                          <span className="text-sm font-bold text-foreground">Oval · 94%</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-muted">Skin Tone</span>
                          <span className="text-sm font-bold text-foreground">Medium · Warm</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-muted">Hair Type</span>
                          <span className="text-sm font-bold text-foreground">Wavy · Thick</span>
                        </div>
                      </div>
                      <div className="space-y-2">
                        {["Long Layers with Soft Waves", "Balayage Highlights", "Glowing Skin Ritual"].map((rec, i) => (
                          <div key={i} className="flex items-center gap-3 rounded-xl bg-surface-3 px-4 py-3">
                            <span className="text-lg">✨</span>
                            <span className="text-sm font-medium text-foreground">{rec}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── AI Stylist ─────────────────────────────────────────────────────── */}
      <GlamBookAIStylist />

      {/* ── AI Finder ──────────────────────────────────────────────────────── */}
      <AiFinder salons={SALONS} />

      {/* ── Salon Explorer ─────────────────────────────────────────────────── */}
      <SalonExplorer salons={SALONS} />

      {/* ── Why GlamBook AI ────────────────────────────────────────────────── */}
      <section className="relative py-28 px-4 sm:px-6 border-t border-white/5">
        <div className="absolute top-0 left-0 right-0 h-[300px] bg-gradient-to-b from-blush/5 to-transparent" />
        <div className="relative mx-auto max-w-7xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full bg-blush-soft border border-blush/20 px-5 py-2 text-sm font-semibold text-blush mb-6">
            💡 Why GlamBook AI is Different
          </span>
          <h2 className="font-display text-4xl font-bold text-foreground sm:text-5xl tracking-tight">
            Built for the{" "}
            <span className="gradient-text-bright">AI Generation</span>
          </h2>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-muted">
            We reimagined what a beauty platform can be — not just listings, but an intelligent
            advisor that understands you.
          </p>

          <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {WHY_GLAMBOOK.map((item, i) => (
              <div
                key={item.title}
                className="glass-card rounded-2xl p-8 text-center transition-all duration-300 hover:-translate-y-2 hover:border-blush/20 hover:shadow-glow-sm"
                style={{ animationDelay: `${i * 100}ms` }}
              >
                <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-blush-soft text-4xl">
                  {item.icon}
                </div>
                <h3 className="font-display text-lg font-bold text-foreground mb-3">
                  {item.title}
                </h3>
                <p className="text-base text-muted leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ──────────────────────────────────────────────────────── */}
      <section className="relative py-32 px-4 sm:px-6">
        <div className="absolute inset-0">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-blush/10 blur-[150px] rounded-full" />
        </div>
        <div className="relative mx-auto max-w-4xl text-center">
          <div className="glass-premium rounded-3xl p-16 relative overflow-hidden">
            {/* Decorative elements */}
            <div className="absolute -top-20 left-1/2 -translate-x-1/2 h-40 w-[400px] rounded-full bg-blush/15 blur-[60px]" />
            <div className="absolute top-10 left-10 w-20 h-20 rounded-full bg-rose-gold/10 blur-[40px]" />
            <div className="absolute bottom-10 right-10 w-24 h-24 rounded-full bg-violet/10 blur-[40px]" />

            <div className="relative">
              <span className="text-6xl mb-8 block">✨</span>
              <h2 className="font-display text-4xl font-bold text-foreground sm:text-5xl tracking-tight">
                Ready to discover your perfect look?
              </h2>
              <p className="mt-6 max-w-lg mx-auto text-lg text-muted">
                Join thousands of women in Mumbai who trust GlamBook AI for their beauty decisions.
                Free to use, no account required.
              </p>
              <div className="mt-12 flex flex-wrap justify-center gap-5">
                <Link
                  href="/beauty-analysis"
                  className="rounded-2xl bg-gradient-to-r from-blush via-blush-bright to-rose-gold px-10 py-5 text-lg font-bold text-white shadow-2xl shadow-blush/30 transition-all hover:scale-105 active:scale-95 hover:shadow-glow-primary btn-glow"
                >
                  🔬 Try AI Beauty Analysis
                </Link>
                <Link
                  href="/#salons"
                  className="glass-card rounded-2xl border border-blush/20 px-10 py-5 text-lg font-semibold text-foreground transition-all hover:border-blush/40 hover:bg-blush-soft/20 hover:scale-105 active:scale-95"
                >
                  💅 Browse Mumbai Salons
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}