import Link from "next/link";
import { SITE_CONFIG } from "@/lib/config";
import { SALONS } from "@/lib/salons";
import { SalonExplorer } from "@/components/SalonExplorer";
import { GlamBookAIStylist } from "@/components/GlamBookAIStylist";
import { AiFinder } from "@/components/AiFinder";
import { AnimatedStats } from "@/components/AnimatedStats";

const AI_FEATURES = [
  {
    href: "/beauty-analysis",
    icon: "🔬",
    title: "AI Beauty Analysis",
    desc: "Upload a selfie. Get face shape, skin tone, hair type & personalized recommendations in 30 seconds.",
    badge: "Most Popular",
    gradient: "from-blush to-blush/60",
  },
  {
    href: "/budget-optimizer",
    icon: "💰",
    title: "AI Budget Optimizer",
    desc: "Enter your budget & occasion. Get the perfect beauty package — optimized by AI.",
    badge: "Smart Savings",
    gradient: "from-gold/80 to-rose-gold/60",
  },
  {
    href: "/occasion-planner",
    icon: "🗓️",
    title: "AI Occasion Planner",
    desc: "From weddings to interviews — get a day-by-day beauty prep timeline generated by AI.",
    badge: "Never Miss a Step",
    gradient: "from-violet/70 to-blush/60",
  },
  {
    href: "/dashboard",
    icon: "📊",
    title: "Salon Owner Dashboard",
    desc: "Real-time analytics, revenue insights, customer trends & demand forecasting.",
    badge: "For Partners",
    gradient: "from-emerald/70 to-blush/50",
  },
];

const WHY_GLAMBOOK = [
  {
    icon: "🧠",
    title: "AI-First Decisions",
    desc: "Not just a booking app — an intelligent beauty advisor that learns your preferences.",
  },
  {
    icon: "🎯",
    title: "Hyper-Personalized",
    desc: "Recommendations based on your actual face shape, skin tone, and hair profile.",
  },
  {
    icon: "⚡",
    title: "One-Tap Booking",
    desc: "From AI recommendation to confirmed appointment in under 60 seconds.",
  },
  {
    icon: "🔒",
    title: "Verified Reviews",
    desc: "Real reviews from real clients. No fakes, no paid promotions.",
  },
];

export default function HomePage() {
  return (
    <>
      {/* ── Hero Section ─────────────────────────────────────────────────── */}
      <section className="relative min-h-[92vh] flex items-center overflow-hidden">
        {/* Background decorations */}
        <div className="absolute inset-0">
          {/* Gradient blobs */}
          <div className="absolute -right-32 -top-20 h-96 w-96 rounded-full bg-blush/10 blur-3xl" />
          <div className="absolute -left-32 bottom-0 h-80 w-80 rounded-full bg-rose-gold/8 blur-2xl" />
          <div className="absolute right-1/4 bottom-1/4 h-64 w-64 rounded-full bg-violet/6 blur-2xl" />
          {/* Grid overlay */}
          <div
            className="absolute inset-0 opacity-[0.03]"
            style={{
              backgroundImage:
                "linear-gradient(rgba(232,121,249,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(232,121,249,0.5) 1px, transparent 1px)",
              backgroundSize: "60px 60px",
            }}
          />
        </div>

        <div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28">
          {/* Badge */}
          <div className="anim-fade-up inline-flex items-center gap-2 rounded-full border border-blush-soft bg-blush-soft/50 px-4 py-1.5 text-xs font-semibold text-blush backdrop-blur-sm mb-8">
            <span className="relative flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-blush opacity-75" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-blush" />
            </span>
            {SITE_CONFIG.tagline}
          </div>

          {/* Headline */}
          <div className="anim-fade-up" style={{ animationDelay: "80ms" }}>
            <h1 className="font-hero max-w-3xl text-5xl font-semibold leading-[1.05] sm:text-6xl lg:text-7xl">
              <span className="text-foreground">Know your look.</span>
              <br />
              <span className="gradient-text">Own your beauty.</span>
            </h1>
          </div>

          <p
            className="anim-fade-up mt-6 max-w-xl text-lg text-muted leading-relaxed sm:text-xl"
            style={{ animationDelay: "160ms" }}
          >
            {SITE_CONFIG.description}
          </p>

          {/* CTA buttons */}
          <div
            className="anim-fade-up mt-10 flex flex-wrap gap-4"
            style={{ animationDelay: "240ms" }}
          >
            <Link
              href="/beauty-analysis"
              className="group flex items-center gap-3 rounded-2xl bg-gradient-to-r from-blush via-blush to-rose-gold px-8 py-4 text-base font-semibold text-white shadow-2xl shadow-blush/20 transition-all hover:scale-105 active:scale-95"
            >
              <span className="text-2xl">🔬</span>
              <div>
                <p>Try AI Beauty Analysis</p>
                <p className="text-xs font-normal opacity-80">Free · 30 seconds</p>
              </div>
            </Link>
            <Link
              href="/#salons"
              className="glass-light flex items-center gap-3 rounded-2xl border border-border px-8 py-4 text-base font-semibold text-foreground transition-all hover:border-blush hover:bg-blush-soft hover:text-blush"
            >
              <span className="text-2xl">💅</span>
              <p>Browse {SALONS.length} Salons</p>
            </Link>
          </div>

          {/* Stats */}
          <div
            className="anim-fade-up mt-16"
            style={{ animationDelay: "320ms" }}
          >
            <AnimatedStats />
          </div>
        </div>
      </section>

      {/* ── AI Features Showcase ──────────────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6">
        <div className="mx-auto max-w-7xl">
          {/* Section header */}
          <div className="text-center mb-14">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-blush-soft border border-blush-soft px-4 py-1.5 text-xs font-semibold text-blush mb-4">
              <span>🚀</span> Four AI Features. One Platform.
            </span>
            <h2 className="font-display text-3xl font-bold text-foreground sm:text-4xl lg:text-5xl">
              Beyond Just a{" "}
              <span className="gradient-text">Salon App</span>
            </h2>
            <p className="mt-4 max-w-xl mx-auto text-muted">
              GlamBook AI transforms how you discover, decide, and book beauty services — powered
              by intelligent analysis and personalized recommendations.
            </p>
          </div>

          {/* Feature cards */}
          <div className="grid gap-5 sm:grid-cols-2">
            {AI_FEATURES.map((feature, i) => (
              <Link
                key={feature.href}
                href={feature.href}
                className="group glass-card rounded-3xl p-7 transition-all duration-300 hover:border-blush/30 hover:-translate-y-1"
                style={{ animationDelay: `${i * 80}ms` }}
              >
                <div className="flex items-start gap-5">
                  <div
                    className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br ${feature.gradient} text-2xl shadow-lg`}
                  >
                    {feature.icon}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-display text-lg font-semibold text-foreground group-hover:text-blush transition-colors">
                        {feature.title}
                      </h3>
                      <span className="rounded-full bg-gold-soft px-2.5 py-0.5 text-[10px] font-semibold text-gold">
                        {feature.badge}
                      </span>
                    </div>
                    <p className="text-sm text-muted leading-relaxed">{feature.desc}</p>
                    <div className="mt-4 flex items-center gap-1 text-xs text-blush font-semibold">
                      <span>Explore feature</span>
                      <span className="transition-transform group-hover:translate-x-1">→</span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── AI Beauty Analysis Preview ────────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6">
        <div className="mx-auto max-w-7xl">
          <div className="glass-card rounded-3xl overflow-hidden">
            <div className="grid lg:grid-cols-2">
              {/* Left: Content */}
              <div className="p-10 sm:p-14 flex flex-col justify-center">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-blush-soft px-3 py-1 text-xs font-semibold text-blush mb-5 w-fit">
                  🔬 AI-Powered · Real Analysis
                </span>
                <h2 className="font-display text-3xl font-bold text-foreground sm:text-4xl leading-tight">
                  Your face tells a story.
                  <br />
                  <span className="gradient-text">AI reads it perfectly.</span>
                </h2>
                <p className="mt-5 text-muted leading-relaxed">
                  Upload a selfie and our AI instantly analyzes your face shape, skin tone, hair
                  type, and condition — then generates personalized hairstyle, makeup, and grooming
                  recommendations just for you.
                </p>
                <ul className="mt-6 space-y-3">
                  {[
                    "Face shape detection with confidence score",
                    "Skin tone analysis with hex values",
                    "Hair type & condition insights",
                    "Personalized look recommendations",
                    "Matched salon recommendations",
                  ].map((item) => (
                    <li key={item} className="flex items-center gap-3 text-sm text-muted">
                      <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blush/20 text-blush text-xs">
                        ✓
                      </span>
                      {item}
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <Link
                    href="/beauty-analysis"
                    className="inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-blush to-rose-gold px-7 py-3.5 text-sm font-semibold text-white shadow-lg hover:opacity-90 transition-all"
                  >
                    🔬 Start AI Beauty Analysis — Free
                  </Link>
                </div>
              </div>

              {/* Right: Mock UI Preview */}
              <div className="relative bg-surface-2 p-8 flex items-center justify-center min-h-[400px]">
                <div className="relative w-full max-w-sm">
                  {/* Phone frame mock */}
                  <div className="rounded-3xl border border-border bg-surface overflow-hidden shadow-2xl">
                    {/* Status bar */}
                    <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-surface-2">
                      <div className="h-1 w-16 rounded-full bg-border" />
                      <div className="h-3 w-3 rounded-full border border-border" />
                    </div>
                    {/* Content */}
                    <div className="p-4 space-y-3">
                      <div className="text-center">
                        <div className="mx-auto mb-3 h-20 w-20 rounded-full bg-gradient-to-br from-blush to-rose-gold flex items-center justify-center text-3xl">
                          🔬
                        </div>
                        <p className="text-sm font-semibold text-foreground">Analyzing your selfie...</p>
                        <div className="mt-2 h-1.5 w-full rounded-full bg-surface-3 overflow-hidden">
                          <div className="h-full w-3/4 rounded-full bg-gradient-to-r from-blush to-rose-gold anim-shimmer" />
                        </div>
                      </div>
                      {/* Analysis results mock */}
                      <div className="glass-light rounded-xl p-3 space-y-2">
                        <div className="flex justify-between items-center">
                          <span className="text-xs text-muted">Face Shape</span>
                          <span className="text-xs font-semibold text-foreground">Oval · 94%</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-xs text-muted">Skin Tone</span>
                          <span className="text-xs font-semibold text-foreground">Medium · Warm</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-xs text-muted">Hair Type</span>
                          <span className="text-xs font-semibold text-foreground">Wavy · Thick</span>
                        </div>
                      </div>
                      <div className="space-y-1.5">
                        {["Long Layers with Soft Waves", "Balayage Highlights", "Glowing Skin Ritual"].map((rec, i) => (
                          <div key={i} className="flex items-center gap-2 rounded-lg bg-surface-3 px-3 py-2">
                            <span className="text-sm">✨</span>
                            <span className="text-xs text-muted">{rec}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                  {/* Glow effect behind */}
                  <div className="absolute -inset-4 bg-gradient-to-br from-blush/10 to-rose-gold/10 blur-2xl -z-10 rounded-3xl" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── AI Stylist ─────────────────────────────────────────────────────── */}
      <GlamBookAIStylist />

      {/* ── AI Finder ──────────────────────────────────────────────────────── */}
      <AiFinder salons={SALONS} />

      {/* ── Salon Explorer ─────────────────────────────────────────────────── */}
      <SalonExplorer salons={SALONS} />

      {/* ── Why GlamBook AI ────────────────────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6 border-t border-blush-soft/20">
        <div className="mx-auto max-w-7xl text-center">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-blush-soft px-4 py-1.5 text-xs font-semibold text-blush mb-4">
            💡 Why GlamBook AI is Different
          </span>
          <h2 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
            Built for the{" "}
            <span className="gradient-text">AI Generation</span>
          </h2>
          <p className="mt-4 max-w-lg mx-auto text-muted">
            We reimagined what a beauty platform can be — not just listings, but an intelligent
            advisor that understands you.
          </p>

          <div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {WHY_GLAMBOOK.map((item, i) => (
              <div
                key={item.title}
                className="glass-light rounded-2xl p-6 text-center transition-all hover:border-blush/20"
                style={{ animationDelay: `${i * 80}ms` }}
              >
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-blush-soft text-3xl">
                  {item.icon}
                </div>
                <h3 className="font-display text-base font-semibold text-foreground mb-2">
                  {item.title}
                </h3>
                <p className="text-sm text-muted">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ──────────────────────────────────────────────────────── */}
      <section className="py-24 px-4 sm:px-6">
        <div className="mx-auto max-w-4xl text-center">
          <div className="glass-card rounded-3xl p-14 relative overflow-hidden">
            {/* Background glow */}
            <div className="absolute -top-20 left-1/2 -translate-x-1/2 h-40 w-96 rounded-full bg-blush/10 blur-3xl" />

            <div className="relative">
              <span className="text-5xl mb-6 block">✨</span>
              <h2 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
                Ready to discover your perfect look?
              </h2>
              <p className="mt-4 max-w-md mx-auto text-muted">
                Join thousands of women in Mumbai who trust GlamBook AI for their beauty decisions.
                Free to use, no account required.
              </p>
              <div className="mt-10 flex flex-wrap justify-center gap-4">
                <Link
                  href="/beauty-analysis"
                  className="rounded-2xl bg-gradient-to-r from-blush to-rose-gold px-8 py-4 text-base font-semibold text-white shadow-2xl shadow-blush/20 transition-all hover:scale-105 active:scale-95"
                >
                  🔬 Try AI Beauty Analysis
                </Link>
                <Link
                  href="/#salons"
                  className="glass-light rounded-2xl border border-border px-8 py-4 text-base font-semibold text-foreground transition-all hover:border-blush hover:text-blush"
                >
                  💅 Browse Mumbai Salons
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}